spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: henning.nobbe
    password: #9Iguodala

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
 
