spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  datasource:
    url: ${ART_DB_URL} # :jdbc:mysql://localhost:3306/artist}
    username: ${ART_DB_U:root}
    password: ${ART_DB_P:geheim01}
  http:
    multipart:
        maxFileSize: 10Mb
        maxRequestSize: 30Mb